feat(forum-theme): update footer FEB23
freeCodeCamp/forum-theme pull request #91
Opened 2023-02-21 11:36 UTC by ahmadabdolsaheb

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2023-02-21 11:40 UTC, ahmadabdolsaheb commented on settings.yml
> +article13title: ""%.2f in Python""
```suggestion
article13title: "%.2f in Python"
```

2023-02-21 11:41 UTC, ahmadabdolsaheb commented on settings.yml
> +article16link: "https://www.freecodecamp.org/news/"check-if-an-item-is-in-an-array-in-javascript-js-contains-with-array-includes/
```suggestion
article16link: "https://www.freecodecamp.org/news/check-if-an-item-is-in-an-array-in-javascript-js-contains-with-array-includes/"
```

2023-02-21 17:37 UTC, naomi-lgbt approved these changes

2023-02-21 17:53 UTC, ShaunSHamilton commented on settings.yml
> +article25title: "What’s a Data Analyst Do?"
Same as the other one. Are we ok with special apostrophes?

```suggestion
article25title: "What's a Data Analyst Do?"
```

2023-02-24 11:32 UTC, ShaunSHamilton requested changes
As pointed out in the other PR

2023-02-24 11:32 UTC, ShaunSHamilton commented on settings.yml
> +article21title: "Remove a Dict in Linux"
```suggestion
article21title: "Remove a Dir in Linux"
```

2023-02-25 11:35 UTC, ahmadabdolsaheb commented on settings.yml
> +article19title: "Python .enumerate()"
```suggestion
article19title: "Python enumerate()"
```

2023-02-27 13:13 UTC, ShaunSHamilton approved these changes

2023-02-27 18:00 UTC, merged