Update settings.yml
freeCodeCamp/forum-theme pull request #99
Opened 2023-06-04 04:49 UTC by ahmadabdolsaheb

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-06-04 07:24 UTC, scissorsneedfoodtoo requested changes
Just noticed one minor issue with a trailing space for one of the links.

All of the links and titles look good, so we should be able to get this in once the trailing space is removed.

2023-06-04 07:24 UTC, scissorsneedfoodtoo commented on settings.yml
> +article23link: "https://www.freecodecamp.org/news/sort-dictionary-by-value-in-python/ "
Minor issue, but there's a trailing space here. It's been fixed in the trending `english.yaml` file on the CDN, and should probably be removed here, too:

```suggestion
article23link: "https://www.freecodecamp.org/news/sort-dictionary-by-value-in-python/"
```

2023-06-04 11:35 UTC, raisedadead commented
Hi @ahmadabdolsaheb - please avoid using GitHub to edit these files. You can use GitPod if you are not feeling like cloning a repo.

It's easy to miss formatting issues. The last time we merged something on the CDN, it broke everything on the main repo. 

cc @ojeytonwilliams

2023-06-04 13:47 UTC, ahmadabdolsaheb commented
Thanks for the heads up.

2023-06-05 03:57 UTC, scissorsneedfoodtoo approved these changes
Took another look and everything LGTM 👍 👍

2023-06-05 03:57 UTC, merged